sonar.projectKey=moldgag_moldgag-ios-app-swift
sonar.organization=moldgag-team

# configs
sonar.sources=.
sonar.language=swift
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/Pods/**,**/Tests/**